# Generated by Django 6.0.6 on 2026-09-17 12:30

from django.db import migrations, models


def remap_verification_required(apps, schema_editor):
    LinkedInProfile = apps.get_model("linkedin", "LinkedInProfile")
    LinkedInProfile.objects.filter(connection_status="verification_required").update(
        connection_status="credentials_saved",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0012_linkedinprofile_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinprofile',
            name='connection_status',
            field=models.CharField(choices=[('not_connected', 'Not connected'), ('credentials_saved', 'Credentials saved'), ('verifying', 'Verifying'), ('checkpoint_required', 'Verification required'), ('connected', 'Connected'), ('session_expired', 'Session expired'), ('error', 'Connection error')], default='not_connected', max_length=32),
        ),
        migrations.RunPython(remap_verification_required, migrations.RunPython.noop),
    ]
